# Generated by Django 5.0.2 on 2024-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_name", models.CharField(max_length=50)),
                ("departure_time", models.DateTimeField()),
                ("seats", models.JSONField(default=list)),
            ],
        ),
    ]
